DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(200) NOT NULL UNIQUE,
	password VARCHAR(200) NOT NULL,
	email VARCHAR(200) NOT NULL UNIQUE
);

SELECT *
FROM users;

CREATE DATABASE postgres2;